version: '3.7'
services:
  web:
    image: nginx:alpine
    #restart: always
    container_name: nginx_arsip
    ports:
     - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./site.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - php
  php:
    image: bitnami/php-fpm
    build:
        context: .
        dockerfile: Dockerfile
    #restart: always
    container_name: php_arsip
    volumes:
      - "./:/var/www/html"
      - "./php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf:ro"
      - "./php-cust.ini:/opt/bitnami/php/etc/conf.d/custom.ini:ro"
    depends_on:
      - db
    #  - redis
      - pdf
  db:
    image: bitnami/mariadb
    #restart: always
    container_name: mysql_arsip
    ports:
        - "3306:3306"
    expose:
        - "3306"
    volumes:
        - "mysql:/bitnami/mariadb"
    environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
        MARIADB_DATABASE: 'arsip_db'
  #redis:
  #  image: redis:alpine
  #  restart: always
  #  container_name: redis_arsip
  #  expose:
  #    - 6379
  pdf:
    image: ciricihq/wkhtmltopdf-aas
    #restart: always
    container_name: wkhtmltopdf
volumes:
  mysql:
    name: mysql
